services:
  next-app:
    container_name: next
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Forward port 3000 on the host to port 80 in the container
    volumes:
      - ./app:/app/app # Sync the src folder for live updates
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
